services:
  - type: web
    name: curalink
    env: node
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    publishDirectory: dist/public
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: GEMINI_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_API_KEY
        sync: false
      - key: TWILIO_API_SECRET
        sync: false